import { 
  DollarSign, 
  ShoppingCart, 
  AlertOctagon, 
  Users, 
  Calendar, 
  Store, 
  FileText, 
  Download, 
  Eye 
} from 'lucide-react';

export default function ReportModule() {
  const reports = [
    { name: 'Sales Report', date: 'May 16, 2025 9:32 AM', by: 'Admin', coverage: 'May 10 - May 16, 2025', format: 'PDF' },
    { name: 'Transaction Report', date: 'May 16, 2025 9:15 AM', by: 'Admin', coverage: 'May 10 - May 16, 2025', format: 'Excel' },
    { name: 'Inventory Report', date: 'May 16, 2025 8:50 AM', by: 'Admin', coverage: 'May 16, 2025', format: 'PDF' },
    { name: 'Worker Incentive Report', date: 'May 16, 2025 8:30 AM', by: 'Admin', coverage: 'May 10 - May 16, 2025', format: 'Excel' },
    { name: 'COP Monitoring Report', date: 'May 16, 2025 8:05 AM', by: 'Admin', coverage: 'May 10 - May 16, 2025', format: 'PDF' },
  ];

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-wrap justify-between items-center gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Report Module</h1>
          <p className="text-xs text-slate-500">Generate sales and transaction reports to track supermarket performance and system activity.</p>
        </div>
        <div className="flex items-center gap-2.5">
          <button className="flex items-center gap-2 border border-slate-200 px-3 py-2 rounded-xl text-xs bg-white text-slate-700 font-medium">
            <Calendar size={14} /> May 10, 2025 - May 16, 2025
          </button>
          <button className="flex items-center gap-2 border border-slate-200 px-3 py-2 rounded-xl text-xs bg-white text-slate-700 font-medium">
            <Store size={14} /> All Branches
          </button>
          <button className="bg-red-50 text-red-600 border border-red-200 px-3 py-2 rounded-xl text-xs font-semibold hover:bg-red-100">
            Export PDF
          </button>
          <button className="bg-emerald-50 text-emerald-700 border border-emerald-200 px-3 py-2 rounded-xl text-xs font-semibold hover:bg-emerald-100">
            Export Excel
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <SmallReportCard icon={DollarSign} label="Total Sales" value="₱125,340.00" sub="↑ 9.65% vs previous 7 days" />
        <SmallReportCard icon={ShoppingCart} label="Total Transactions" value="942" sub="↑ 8.21% vs previous 7 days" />
        <SmallReportCard icon={AlertOctagon} label="Low Stock Incidents" value="23" sub="↓ 8.33% vs previous 7 days" isRed />
        <SmallReportCard icon={Users} label="Worker Tip Payouts" value="₱8,915.75" sub="↑ 11.47% vs previous 7 days" />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-5 gap-3.5">
        {['Sales Report', 'Transaction Report', 'Inventory Report', 'Worker Incentive Report', 'COP Monitoring Report'].map((title, i) => (
          <div key={i} className="bg-white p-4 rounded-2xl border border-slate-200 hover:border-emerald-500 cursor-pointer transition-all shadow-2xs">
            <div className="w-8 h-8 rounded-lg bg-emerald-50 text-emerald-600 flex items-center justify-center mb-2"><FileText size={16} /></div>
            <h4 className="text-xs font-bold text-slate-800">{title}</h4>
            <p className="text-[10px] text-slate-400 mt-1">View summary & movement</p>
          </div>
        ))}
      </div>

      <div className="bg-white rounded-2xl border border-slate-200 p-6 shadow-sm">
        <h3 className="font-bold text-slate-800 mb-4">Recent Reports</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="text-slate-400 border-b border-slate-100">
                <th className="pb-3 font-semibold">Report Name</th>
                <th className="pb-3 font-semibold">Date Generated</th>
                <th className="pb-3 font-semibold">Generated By</th>
                <th className="pb-3 font-semibold">Coverage</th>
                <th className="pb-3 font-semibold">Format</th>
                <th className="pb-3 font-semibold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {reports.map((r, i) => (
                <tr key={i} className="hover:bg-slate-50/50">
                  <td className="py-3 font-bold text-slate-700">{r.name}</td>
                  <td className="py-3 text-slate-500">{r.date}</td>
                  <td className="py-3 text-slate-600">{r.by}</td>
                  <td className="py-3 text-slate-500">{r.coverage}</td>
                  <td className="py-3">
                    <span className={`px-2 py-0.5 rounded-md text-[10px] font-bold ${r.format === 'PDF' ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-700'}`}>
                      {r.format}
                    </span>
                  </td>
                  <td className="py-3 text-right">
                    <div className="flex items-center justify-end gap-2 text-slate-400">
                      <button className="hover:text-emerald-700 p-1"><Download size={15} /></button>
                      <button className="hover:text-emerald-700 p-1"><Eye size={15} /></button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

function SmallReportCard({ icon: Icon, label, value, sub, isRed }) {
  return (
    <div className="bg-white p-4 rounded-2xl border border-slate-200 flex items-center gap-4">
      <div className={`w-12 h-12 rounded-xl flex items-center justify-center shrink-0 ${isRed ? 'bg-red-50 text-red-600' : 'bg-emerald-50 text-emerald-600'}`}>
        <Icon size={22} />
      </div>
      <div>
        <p className="text-[11px] text-slate-400 font-medium">{label}</p>
        <p className="text-xl font-bold text-slate-800 leading-tight">{value}</p>
        <p className="text-[10px] text-slate-400 mt-0.5">{sub}</p>
      </div>
    </div>
  );
}